### ISSUE TITLE
TypeError when trying to load a custom extension

### ISSUE THREAD

**Issue by tanepiper** [showdownjs/showdown#392]
I'm currently writing this extension:

```js
(function(extension) {
  'use strict';
  if (typeof showdown !== 'undefined') {
    // global (browser or nodejs global)
    extension(showdown);
  } else if (typeof define === 'function' && define.amd) {
    // AMD
    define(['showdown'], extension);
  } else if (typeof exports === 'object') {
    // Node, CommonJS-like
    module.exports = extension(require('showdown'));
  } else {
    // showdown was not found so we throw
    throw Error('Could not find showdown library');
  }
})(function(showdown) {
  'use strict';
  // loading extension into showdown

  var steps = [
    {
      type: 'lang',
      regex: '/\.\/docs\/assets\/',
      replace: function() {
        return './../assets/';
      }
    }
  ];
  showdown.extension('imagePath', function() {
    return steps;
  });
});
```

I invoke it like this:

```js
var showdown = require('showdown');
var fs = require('fs');
var path = require('path');

var imagePath = require('./image-path.showdown');

var converter = new showdown.Converter({extensions: [imagePath]});

var readme = path.resolve(__dirname, '..', 'README.md');

fs.readFile(readme, 'utf8', function (error, data) {
    console.log(data);
    if (error) {
        throw error;
    }
    var html = converter.makeHtml(data);
    console.log(html);  // TODO: Output to files
});    
```

When I try import this in my current script I get:

```js
/Users/me/work/project/node_modules/showdown/dist/showdown.js:562
  return a.constructor === Array;
          ^

TypeError: Cannot read property 'constructor' of undefined
    at Object.showdown.helper.isArray (/Users/me/work/project/node_modules/showdown/dist/showdown.js:562:11)
    at _parseExtension (/Users/me/work/project/node_modules/showdown/dist/showdown.js:980:26)
    at Array.forEach (native)
    at Object.showdown.helper.forEach (/Users/me/work/project/node_modules/showdown/dist/showdown.js:599:9)
    at _constructor (/Users/me/work/project/node_modules/showdown/dist/showdown.js:942:23)
    at new showdown.Converter (/Users/me/work/project/node_modules/showdown/dist/showdown.js:914:3)
    at Object.<anonymous> (/Users/me/work/project/support/doc-generator.js:7:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

Any help on this would be appreciated.

**Comment by tivie** [comment]
(Not tested)

Replace this

    showdown.extension('imagePath', function() {
      return steps;
    });

With this:

    return steps;


And then see if it works and give feedback here

**Comment by tivie** [comment]
Closing as no activity for 1 month
